const fs = require('fs');
const path = require('path');
const { v4: uuidv4 } = require('uuid');

const API_DIR = path.join(__dirname, 'app', 'api');
const OUTPUT_FILE = path.join(__dirname, 'KIKA_Postman_Collection.json');

const collection = {
    info: {
        _postman_id: uuidv4(),
        name: "KIKA System API Collection",
        description: "Autogenerated comprehensive API reference and simulation journeys for the KIKA system.",
        schema: "https://schema.getpostman.com/json/collection/v2.1.0/collection.json"
    },
    item: [
        {
            name: "API Reference Catalog",
            description: "Comprehensive map of all available endpoints in the system.",
            item: [] // Will be populated by parsing the directory
        },
        {
            name: "Simulation Journeys",
            description: "Sequential workflows leveraging Postman Runner.",
            item: [] // To be populated manually/programmatically later
        }
    ],
    variable: [
        { key: "baseUrl", value: "http://localhost:3000", type: "string" },
        { key: "admin_token", value: "", type: "string" },
        { key: "member_token", value: "", type: "string" },
        { key: "regulator_token", value: "", type: "string" },
        { key: "vendor_token", value: "", type: "string" },
        { key: "external_auditor_token", value: "", type: "string" }
    ]
};

function readDirRecursive(dir, routePrefix = '') {
    let items = [];
    const files = fs.readdirSync(dir);

    for (const file of files) {
        const fullPath = path.join(dir, file);
        const stat = fs.statSync(fullPath);

        if (stat.isDirectory()) {
            const folderName = file;
            const folderItems = readDirRecursive(fullPath, `${routePrefix}/${folderName}`);

            if (folderItems.length > 0) {
                items.push({
                    name: folderName,
                    item: folderItems
                });
            }
        } else if (file === 'route.ts' || file === 'route.js') {
            // Found an API endpoint

            // Just creating a default POST and GET request for each route for now
            // In a real scenario, we'd parse the AST to see exactly what methods are exported (GET, POST, etc.)
            // For this massive script, we'll assume GET and POST as placeholders unless we do deeper parsing.

            // Let's read the file contents to see what methods it exports
            const content = fs.readFileSync(fullPath, 'utf8');
            const methods = [];
            if (content.includes('export async function GET')) methods.push('GET');
            if (content.includes('export async function POST')) methods.push('POST');
            if (content.includes('export async function PUT')) methods.push('PUT');
            if (content.includes('export async function PATCH')) methods.push('PATCH');
            if (content.includes('export async function DELETE')) methods.push('DELETE');

            // Fallback if it uses generic handler approach
            if (methods.length === 0) {
                methods.push('GET'); // Default assumption
            }

            for (const method of methods) {
                const urlParts = routePrefix.split('/').filter(Boolean); // e.g. ['admin', 'accounting', 'general-ledger']
                // Let's replace Next.js dynamic routes (e.g. [id]) with Postman variables (:id)
                const postmanPath = urlParts.map(part => {
                    if (part.startsWith('[') && part.endsWith(']')) {
                        const paramName = part.substring(1, part.length - 1);
                        return `:${paramName}`;
                    }
                    return part;
                });

                // Determine Auth token based on folder path
                let tokenVar = "{{admin_token}}";
                if (urlParts.includes('member') || urlParts.includes('members')) tokenVar = "{{member_token}}";
                if (urlParts.includes('regulator')) tokenVar = "{{regulator_token}}";
                if (urlParts.includes('vendor')) tokenVar = "{{vendor_token}}";
                if (urlParts.includes('external-auditor')) tokenVar = "{{external_auditor_token}}";
                if (urlParts.includes('public') || urlParts.includes('registration') || urlParts.includes('auth')) {
                    tokenVar = null; // No auth
                }

                const requestItem = {
                    name: `[${method}] ${routePrefix}`,
                    request: {
                        method: method,
                        header: [
                            {
                                key: "Content-Type",
                                value: "application/json",
                                type: "text"
                            }
                        ],
                        url: {
                            raw: `{{baseUrl}}/api${routePrefix}`,
                            host: ["{{baseUrl}}"],
                            path: ["api", ...postmanPath],
                        }
                    },
                    response: []
                };

                // Add Auth header if needed
                if (tokenVar) {
                    requestItem.request.header.push({
                        key: "Authorization",
                        value: `Bearer ${tokenVar}`,
                        type: "text"
                    });
                }

                // Add empty body for POST/PUT/PATCH
                if (['POST', 'PUT', 'PATCH'].includes(method)) {
                    requestItem.request.body = {
                        mode: "raw",
                        raw: "{\n    \n}",
                        options: {
                            raw: {
                                language: "json"
                            }
                        }
                    };
                }

                items.push(requestItem);
            }
        }
    }
    return items;
}

const apiItems = readDirRecursive(API_DIR);
collection.item[0].item = apiItems;

fs.writeFileSync(OUTPUT_FILE, JSON.stringify(collection, null, 2));
console.log(`Generated ${OUTPUT_FILE} with ${apiItems.length} root level folders/items (Total endpoints parsed deeply).`);
