import type { User } from './User';

export enum ApplicationType {
    GENERAL_SOCIETY = 'general_society',
    BURIAL_SOCIETY = 'burial_society',
    RELIGIOUS_SOCIETY = 'religious_society',
    SACCOS = 'saccos',
    COOPERATIVE = 'cooperative',
}

export enum ApplicationStatus {
    DRAFT = 'draft',
    SUBMITTED = 'submitted',
    INCOMPLETE = 'incomplete',
    UNDER_REVIEW = 'under_review',
    SECURITY_VETTING = 'security_vetting',
    SECURITY_FAILED = 'security_failed',
    LEGAL_REVIEW = 'legal_review',
    LEGAL_REJECTED = 'legal_rejected',
    PENDING_DECISION = 'pending_decision',
    APPROVED = 'approved',
    REJECTED = 'rejected',
    APPEAL_LODGED = 'appeal_lodged',
    APPEAL_APPROVED = 'appeal_approved',
    APPEAL_REJECTED = 'appeal_rejected',
}
export class SocietyApplication {
    id!: string;
    fileNumber?: string; // Auto-generated by Registry Clerk (e.g., GS-2026-001)
    applicationType!: ApplicationType;
    proposedName!: string;
    status!: ApplicationStatus;

    // Applicant info
    applicantUserId!: string;
    applicant?: User;
    primaryContactName!: string;
    primaryContactEmail!: string;
    primaryContactPhone!: string;
    physicalAddress!: string;

    // Workflow tracking
    submittedAt?: Date;
    assignedFileNumberAt?: Date;
    securityClearedAt?: Date;
    legalApprovedAt?: Date;
    finalDecisionAt?: Date;
    securityVettingNotes?: string;

    // Decision makers
    registryClerkId?: string;
    registryClerk?: User;
    intelligenceLiaisonId?: string;
    intelligenceLiaison?: User;
    legalOfficerId?: string;
    legalOfficer?: User;
    finalDecisionMakerId?: string; // Registrar or Director
    finalDecisionMaker?: User;

    // Outcomes
    certificateNumber?: string;
    certificateIssuedAt?: Date;
    rejectionReasons?: string;

    // Appeal
    appealLodgedAt?: Date;
    appealDecisionAt?: Date;
    appealDecisionMakerId?: string;
    appealDecisionMaker?: User;
    appealOutcome?: string;

    // Fees
    feeAmount!: number;
    feePaidAt?: Date;
    createdAt!: Date;
    updatedAt!: Date;

    // Helper methods
    get isApproved(): boolean {
        return this.status === ApplicationStatus.APPROVED || this.status === ApplicationStatus.APPEAL_APPROVED;
    }

    get isRejected(): boolean {
        return this.status === ApplicationStatus.REJECTED ||
            this.status === ApplicationStatus.SECURITY_FAILED ||
            this.status === ApplicationStatus.LEGAL_REJECTED ||
            this.status === ApplicationStatus.APPEAL_REJECTED;
    }

    get canAppeal(): boolean {
        if (!this.isRejected || this.status === ApplicationStatus.APPEAL_REJECTED) {
            return false;
        }

        // Check if within 21 days of rejection
        const rejectionDate = this.finalDecisionAt;
        if (!rejectionDate) return false;

        const now = new Date();
        const daysSinceRejection = Math.floor((now.getTime() - rejectionDate.getTime()) / (1000 * 60 * 60 * 24));

        return daysSinceRejection <= 21;
    }

    get requiredFee(): number {
        // If a specific fee amount was set at creation/approval time, use that
        if (this.feeAmount && Number(this.feeAmount) > 0) {
            return Number(this.feeAmount);
        }

        // Fallback for draft/legacy applications
        switch (this.applicationType) {
            case ApplicationType.RELIGIOUS_SOCIETY:
                return 500; // BWP 500 for churches
            case ApplicationType.SACCOS:
                return 20; // BWP 20 for SACCOS
            case ApplicationType.GENERAL_SOCIETY:
            case ApplicationType.BURIAL_SOCIETY:
            default:
                return 250; // BWP 250 for general societies
        }
    }

    get isPaid(): boolean {
        return this.feePaidAt !== null && this.feeAmount >= this.requiredFee;
    }
}
